---
name: Logan Stundal
date: "`r format(Sys.time(), '%B, %Y')`"
qualifications: PhD
position: PhD Candidate
address: Minneapolis, MN
phone: 701 610 8586
email: stund005@umn.edu
www: loganstundal.com
github: loganstundal
# linkedin: loganstundal
twitter: loganstundal
headcolor: 414141
output: vitae::awesomecv
keep_tex: true
header-includes:
   - \usepackage{xcolor}
   - \definecolor{fontColor}{HTML}{414141}
# knit: (function(inputFile, encoding) { 
#     rmarkdown::render(inputFile, 
#                       encoding    = encoding, 
#                       output_file = file.path(dirname(inputFile),
#                                               'Versions',
#                                               paste0('VITAE_',format(lubridate::today(), "%Y%m%d")))) 
#                       })
---

```{r setup, include=FALSE}
library(tidyverse)
library(vitae)
knitr::opts_chunk$set(echo = FALSE)
```

\vspace{0.5in}
# Education
```{r}
umn <- tribble(
  ~ degree, ~ uni, ~ loc, ~ dates,
  "PhD, Political Science", "University of Minnesota", "Minneapolis, MN", "2016 - Present",)

umn.details <- c("Fields: International Relations and Political Methods",
                 "Advisors: Tanisha Fazal, John Freeman")

und <- tribble(
  ~ degree, ~ uni, ~ loc, ~ dates,
  "BA, Political Science and Economics", "University of North Dakota", "Grand Forks, ND", "2013"
)
und.details <- c("Magna Cum Laude")



detailed_entries(data = umn, what = degree, when = dates, 
                 with = uni, where = loc, why = umn.details)
detailed_entries(data = und, what = degree, when = dates, 
                 with = uni, where = loc, why = und.details,.protect=F)

```


# Dissertation
```{r}
tribble(~title, ~abstract,
        "The Epidemiology of Civil Wars", 
        "My dissertation explores the causal relationship between the dynamics of civil war and the outbreak of disease within these environments. It examines how certain classes of conflict produce differential civilian strategic responses which yield different disease outbreak outcomes. Cross-national and sub-national dynamic spatial models demonstrate theoretical generalizability while detailed case analysis of the Syrian civil war illuminates causal mechanisms.") %>%
  detailed_entries(what = title,
                   why  = abstract)
```


# Relevant Skills
## Data Analysis
```{r}
tribble(~detail,
        "Spatial Econometrics, Mapping, Time Series, Bayesian Analysis, Visualisation, Data Cleaning, Surveys",
        ) %>%
  brief_entries(detail)
```

## Programming
```{r}
tribble(~detail,
        "R, Python, SQL, Stan, LaTeX, Git, Javascript"
        ) %>%
  brief_entries(detail)
```

## Research Interests
```{r}
tribble(~detail,
        "\\textbf{International Relations}: Disease outbreaks, civil wars, conflict dynamics, conflict data validation",
        "\\textbf{Methodology}: spatial models, diffusion and contagion processes, Bayesian analsysis, simulation, event data"
        ) %>%
  brief_entries(detail,.protect = F)
```


# Working Papers
```{r}
tribble(~title, ~coauthors,
        "Event Data in Space: Spatial Models of Machine Coded Vs. Human Coded Conflict Data", 
        "(with Benjamin Bagozzi, John Freeman, and Jennifer Holmes), Presented at PolMeth 2019",
        "Media Sentiment and Chinese Foreign Policy: Classifying Reporting with Convolutional Neural Nets",
        "(with Matt Eichinger)",
        "Rebel Predation and Foreign Aid", "Presented at MPSA 2019") %>%
  detailed_entries(why = coauthors,what = title)
```


# Non-academic writing
```{r}
tribble(~entry,~when,
        "``Measles, Ukraine, and Civil War: The Missing Links'' (with Tanisha Fazal). \\it{Political Violence @ A Glance}", "March 22, 2019") %>%
  detailed_entries(what = entry, 
                   when = when,.protect=F)
```


\newpage
# Awards, Grants, & Fellowships
```{r}
tribble(
  ~name, ~year,
  "Political Science, Teaching Assistant Fellowship", "2017-Present",
  "Political Science, Summer Fellowship", "2017-Present",
  "National Science Foundation, GRFP Honorable Mention", "2018",
  "Graduate Pre-Dissertation Research Fellowship", "2017",
  "Larson Graduate Research Fellowship in Political Economy", "2016-17",
  "EITM Certification / Fellowship - ICPSR (NSF Funded)", "2017",
  "PolMeth Travel Grant, Madison, WI (NSF Funded)", "2017",
  "Ronald E. McNair Post-Baccalaureate Fellowship", "2009-13"
  
  ) %>%
  brief_entries(what = name,
                with = year)

```


# Teaching and Research Experience
```{r}
tribble(~what,'Primary Instructor') %>%
  detailed_entries(what = what,
                   why  = c('POL 3085: Quantitative Analysis'))

tribble(~what, ~why,
        'Teaching Assistant',
        c('POL 1025: Global Politics; POL 1026: Foreign Policy; POL 3085: Quantitative Analysis; POL 4810: The Politics of Nuclear Weapons')) %>%
  detailed_entries(what = what,
                   why  = why)

tribble(~what,'Research Assistant') %>%
  detailed_entries(what = what,
                   why  = c('John Freeman: Summer 2018 - present',
                            'Ron Krebs: Fall 2019',
                            'Jessica Stanton: Summer 2018'))

```


# Conference & Workshop Participation
Annual Meetings 
```{r}
tribble(~name, ~year,
        "Polmeth", "2017, 2019",
        "Midwest Political Science Association", "2019,2020",
        "Upper Midwest International Relations Conference", "2018, 2019, 2020") %>%
  brief_entries(what = name,
                with = year)
```

Workshops
```{r}
tribble(~name, ~year,
        "BIGCSS Summer School in Computational Social Science (Breman, Germany)", "Summer 2018",
        "ICPSR, University of Michigan, Ann Arbor", "Summer 2017") %>%
  brief_entries(what = name,
                with = year)
```


# Service
```{r}

tribble(
  ~name, ~year,
  "Minnesota Graduate Student Methods Conference, Organizer", "2018-Present",
  "Minnesota Political Methods Colloquium, Co-Chair", "2018-Present",
  "McNair Program: Student Mentor","2017-Present",
  "Graduate Student Life Committee, Co-Chair", "2018-19",
  "TRIO Program - Upward Bound: Mentor", "2016"
  ) %>%
  brief_entries(what = name,
                with = year)
```


# Affiliations
```{r}
tribble(~what,
        "Society for Political Methodology",
        "Midwest Political Science Association",
        "International Studies Association") %>%
  brief_entries(what = what)
```


# Awards & Achievements
Awards
```{r}
tribble(
  ~ award, ~ year,
  "UMN, Thank a Teacher Award", "2019, 2018",
) %>%
  brief_entries(what = award, 
                with = year)
```

<!-- \pagebreak -->

<!-- # References -->
<!-- \begin{table}[!h] -->
<!--   \fontsize{10}{4} -->
<!--   \selectfont -->
<!--   {\color{fontColor}\begin{tabular*}{\textwidth}{@{\extracolsep{\fill}} lll} -->
<!--     John Freeman                                & Tanisha Fazal                     & Jessica Stanton \\ -->
<!--     Professor                                   & Associate Professor               & Associate Professor\\ -->
<!--     Political Science Department                & Political Science Department      & Humphrey School of Public Affairs\\ -->
<!--     University of Minnesota                     & University of Minnesota           & University of Minnesota \\ -->
<!--     Email: \href{mailto:freeman@umn.edu}{freeman@umn.edu} & -->
<!--     Email: \href{mailto:fazal007@umn.edu}{fazal007@umn.edu} & -->
<!--     Email: \href{mailto:stantonj@umn.edu}{stantonj@umn.edu} \\ -->
<!--     Phone: 612-624-6018                         & Phone: 612-624-8261 \             & 612-626-8910 \\ -->
<!--     & & \\ -->
<!--     & & \\ -->
<!--     & & \\ -->
<!--     Jane Sumner                                 & Mark Bell                         & Brian Urlacher \\ -->
<!--     Assistant Professor                         & Assistant Professor               & Professor \\ -->
<!--     Political Science Department                & Political Science Department      & Political Science Department\\ -->
<!--     University of Minnesota                     & University of Minnesota           & University of North Dakota \\ -->
<!--     Email: \href{mailto:jlsumner@umn.edu}{jlsumner@umn.edu} & -->
<!--     Email: \href{mailto:msbell@umn.edu}{msbell@umn.edu} & -->
<!--     Email: \href{mailto:brian.urlacher@und.edu}{brian.urlacher@und.edu} \\ -->
<!--     Phone: 612-626-7825                         & Phone: 612-626-2889               & Phone: 701-777-3541 -->


<!--   \end{tabular*}} -->
<!-- \end{table} -->


